core_files:
    # LLM clients
  - path: src/clients/unified_client.py
    description: Unified LLM Client
  - path: src/clients/openai_client.py
    description: Openai LLM Client
  - path: src/clients/ollama_client.py
    description: Ollama LLM Client
    
    # Datastore
  - path: src/datastore/common.py
    description: Base datastore
  - path: src/datastore/benchmarks.py
    description: Benchmarks datastore

    # Lib
  - path: src/lib/score_table.py
    description: Score table generator
  - path: src/lib/benchmarks/base.py
    description: Base class for benchmarks
  - path: src/lib/benchmarks/base_generator.py
    description: Base class for benchmark generators
  - path: src/lib/benchmarks/base_runner.py
    description: Base class for benchmark runners
  - path: src/lib/benchmarks/data_models.py
    description: Data classes for benchmarks
  - path: src/lib/benchmarks/factory.py
    description: Factory for benchmarks
  - path: src/lib/benchmarks/registry.py
    description: Registry for benchmarks
  - path: src/lib/benchmarks/run_benchmark.py
    description: Helpers to run benchmarks

    # Sample benchmarks

  - path: src/lib/benchmarks/part_of_speech_generator.py
    description: Part-of-speech benchmark generator
  - path: src/lib/benchmarks/part_of_speech_runner.py
    description: Part-of-speech benchmark runner

    templates:
  - path: templates/model_scores.html
    description: Model scores main page template
  - path: templates/run_details.html
    description: Individual run details template
